Refactor parse_dtbo_metadata
radxa-pkg/rsetup pull request #28
Opened 2024-01-04 09:28 UTC by CodeChenL

2024-01-05 03:36 UTC, RadxaYuntian requested changes
另外重构还是要一步步来，先弄两个python脚本分别代替parse_dtbo和dtbo_is_compatible，这样我们可以确定功能没有regression，然后再来更改整体架构

2024-01-05 03:44 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +#argv[1]:   0,1         compatible dtbo
-a -b这种形式吗，还是是说不要用0,1

2024-01-05 03:48 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +compatible= open("/sys/firmware/devicetree/base/compatible").read()
那我可不可以把兼容型号改成由shell传入，参数为空时不判断兼容

2024-01-05 03:52 UTC, CodeChenL commented
> 另外重构还是要一步步来，先弄两个python脚本分别代替parse_dtbo和dtbo_is_compatible，这样我们可以确定功能没有regression，然后再来更改整体架构

这样的话就要读两次dtbo,有点浪费性能

2024-01-05 03:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +#argv[1]:   0,1         compatible dtbo
比如加一个`--is-compatible`的flag，然后只接受dtbo文件名，并返回兼容的文件

2024-01-05 03:58 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +            for dtbo_compatible in metadata["compatible"][0].split("\x00"):
你可能review的代码不是最新的，最新的注释修改了

2024-01-05 03:58 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +compatible= open("/sys/firmware/devicetree/base/compatible").read()
先拆分成两个脚本

2024-01-05 03:59 UTC, RadxaYuntian commented
> > 另外重构还是要一步步来，先弄两个python脚本分别代替parse_dtbo和dtbo_is_compatible，这样我们可以确定功能没有regression，然后再来更改整体架构
> 
> 这样的话就要读两次dtbo,有点浪费性能

问题是你现在的改动有regression，只有正确的实现才有考虑性能的价值。不要过早优化

2024-01-05 03:59 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +            for dtbo_compatible in metadata["compatible"][0].split("\x00"):
大方向没变，先从简单的改动开始，慢慢过渡到整体的改变

2024-01-08 03:37 UTC, RadxaYuntian requested changes
commit历史整理一下，分成两个commit对应两个新增的python脚本。

2024-01-08 03:37 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
>      if [[ ! -f /sys/firmware/devicetree/base/compatible ]]
这个判断移动到python里面去

2024-01-08 03:37 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    local showchecked="$2"
目前没有这个功能的需求认在__overlay_info里面把当前开启的overlay也选中是可以的。重构一般不要加新功能

2024-01-08 03:41 UTC, RadxaYuntian requested changes

2024-01-08 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    __overlay_filter "$temp"
现在并行都做到python里面去了，可以把这个函数及其子函数都删了，把实际的执行逻辑放到__overlay_show里面

2024-01-08 03:43 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    local showchecked="$2"
因为在overlays界面会显示，enable的overlay,我就加了这个功能，要去掉吗

2024-01-08 03:58 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    local showchecked="$2"
是的，因为当时添加这个功能是为了能够让用户方便的查看当前开启的overlay所使用的引脚，方便进行连接或者技术支持，所以这个功能目前没有必要。

2024-01-08 04:00 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    local showchecked="$2"
好的，我以为是我造成的bug所以加了这个功能😂

2024-01-08 07:13 UTC, RadxaYuntian requested changes

2024-01-08 07:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_compatible
> +
print完了应该要exit(0)出去吧？不然会继续执行下面的逻辑

2024-01-08 07:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_compatible
> +        print(file)
重构逻辑，加一个is_compatible函数在内部循环检测，然后外面的files循环根据函数的返回值来打印文件名

2024-01-08 07:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_compatible
> +        stderr.write(e)
exit(1)终止程序执行

2024-01-08 07:13 UTC, RadxaYuntian commented
接下来的更改就不要重写提交历史了，先独立commit

2024-01-08 07:17 UTC, RadxaYuntian requested changes
u-boot-menu.sh第67行也用了dtbo_is_compatible，需要修改来适应现在的返回条件。但代码本身可以暂时不做更改，因为这边用户通常不会直接面对

2024-01-08 07:30 UTC, RadxaYuntian requested changes

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +parser.add_argument('-S', action='store_true', default=False, help='Print short info')
你这边绝大多数的调用都是-S，就应该默认是这个模式，if args.F else后执行

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +parser.add_argument('-F', action='store_true', default=False, help='Print full info')
换个名字，full info并不能表达这个选项是仅限overlay_show里面使用的

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +parser = argparse.ArgumentParser(description='Simulate script command with custom options.')
description写的有问题

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +parser.add_argument('-f', nargs='+', metavar='filename', help='DTBO Filenamelist')
这个应该是一个positional argument：https://docs.python.org/zh-cn/3/library/argparse.html

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +parser.add_argument('-c', metavar='string', default="title", help='Keyword')
这也应该是一个positional argument。凡是程序执行所必须的参数都应该优先考虑设置成positional

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
-e "$default"删掉，只在需要override默认返回值的地方再加上这个参数

2024-01-08 07:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo_metadata
> +    for file in args.f:
应该为两个模式分别写两个打印函数，然后循环里面根据当前模式调用不同函数

2024-01-08 09:02 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
你的意思是在shell覆写python的输出吗

2024-01-08 09:02 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
没事了，我理解你的意思了

2024-01-08 09:08 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
那不对啊，我们调用 parse_dtbo的长度是不固定的，无法判断要不要override啊

2024-01-08 09:10 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
所以每次调用都写parse_dtbo ＄3

2024-01-08 09:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
你的python里面不是给这个参数赋了个null的默认值么？不加参数就等于`-e null`吧

2024-01-08 09:11 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
还是说你的意思就是在shell覆写python的输出

2024-01-08 09:12 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
> 你的python里面不是给这个参数赋了个null的默认值么？不加参数就等于`-e null`吧

可是在L139里怎么确定有没有override呢

2024-01-08 09:14 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
要么就直接调用$PARSE_DTBO_METADATA

2024-01-08 09:14 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
不调用parse_dtbo

2024-01-08 09:14 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
直接由调用方在“$@”里面传入

2024-01-08 09:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
我觉得可以在rsetup初始化代码里，把那个目录加到PATH里面，然后直接调用脚本就可以了，不用这些变量和函数wrap它

2024-01-08 09:17 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
那我能把src/usr/lib/rsetup/cli/u-boot-menu.sh里的两个方法删了吗

2024-01-08 09:23 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    "$PARSE_DTBO_METADATA" -c "$keyword" -e "$default" "$Full" -f "$@"
可以的

2024-01-08 10:38 UTC, CodeChenL commented
涉及python脚本的commit不是很细，因为改名了

2024-01-08 11:13 UTC, RadxaYuntian requested changes

2024-01-08 11:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_compatible
> +    if is_compatible(file,metadata,compatible):
参数用空格分隔

2024-01-08 11:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    if [ -n "$(dtbo_is_compatible "$overlay")" ]
bash下默认用[[ ]]进行判断

2024-01-08 11:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    except KeyError:
应该把这个exception在is_compatible里面处理

2024-01-08 11:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +def basename(file):
加个空行

2024-01-08 11:16 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_compatible
>  except FileNotFoundError as e:
除了找不到文件，其他错误都会退出

2024-01-08 11:35 UTC, RadxaYuntian requested changes

2024-01-08 11:35 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    except KeyError:
加个注释说明如果KeyError则认为是用户自行安装的第三方overlay，默认兼容

2024-01-08 11:37 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    except KeyError:
对呀，就是返回的true呀

2024-01-08 11:38 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    except KeyError:
加个注释说明为什么返回true

2024-01-08 11:39 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    except KeyError:
哦，把前面看漏了，不好意思

2024-01-08 11:49 UTC, RadxaYuntian requested changes

2024-01-08 11:49 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    if [[ -n $(dtbo_is_compatible "$overlay") ]]
```suggestion
    if [[ -n “$(dtbo_is_compatible "$overlay")” ]]
```
虽然bash不会把$()输出的带空格内容解释为语法错误，但由于其他的地方很多时候仍需要将其用引号包裹，从代码规范的角度是要求始终用引号，以免在进行代码复制粘贴的时候粘贴到了没有语法保护的地方

2024-01-08 12:39 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    mapfile -t name < <(parse_dtbo "--default-value" "file" "title" "$1")
```suggestion
    mapfile -t name < <(parse_dtbo --default-value "file" "title" "$1")
```

2024-01-08 12:39 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    mapfile -t items < <(parse_dtbo "--show-overlays" "title" "${dtbos[@]}")
```suggestion
    mapfile -t items < <(parse_dtbo --show-overlays "title" "${dtbos[@]}")
```

2024-01-08 12:39 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +        mapfile -t title < <(parse_dtbo "--default-value" "file"  "title" "$U_BOOT_FDT_OVERLAYS_DIR/$item"*)
```suggestion
        mapfile -t title < <(parse_dtbo --default-value "file"  "title" "$U_BOOT_FDT_OVERLAYS_DIR/$item"*)
```

2024-01-08 13:01 UTC, merged