Add functions "USB OTG port functions"
radxa-pkg/rsetup pull request #32
Opened 2024-01-24 09:43 UTC by CodeChenL

2024-01-24 12:13 UTC, RadxaYuntian requested changes

2024-01-25 03:49 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +Select any to update their status." || (( ${#RSETUP_CHECKLIST_STATE_NEW[@]} == 0 ))
检查一下如果在对应页面取消时是否会返回到hardware菜单

2024-01-25 04:11 UTC, RadxaYuntian requested changes

2024-01-25 04:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +    fi
这里udc_function_string应该是一个数组，然后把结果数组转换成多行字符串（`printf "%s\n"  "${System[@]}"`），然后再用grep筛选。bash里面避免字符串拼接操作

2024-01-25 04:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +    for ((i = 0; i < length; i+=3))
这里可以改成循环${#RSETUP_CHECKLIST_STATE_NEW[@]}

2024-01-25 04:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        status="${RSETUP_CHECKLIST[i+2]}"
这里udc_function改成用checklist_getitem获取，status直接从RSETUP_CHECKLIST_STATE_NEW[i]里面获取

2024-01-25 04:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        elif [[ "$status" == "OFF" ]]
这里直接else吧

2024-01-25 06:44 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +    for ((i = 0; i < length; i+=3))
可是我要在一次循环索引多个元素

2024-01-25 08:13 UTC, RadxaYuntian requested changes

2024-01-25 08:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        checklist_add "$service" "OFF"
case内部增加一级缩进

2024-01-25 08:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +    if [[ $(printf "%s\n"  "${udc_function_list[@]}" | grep -o "radxa-adbd@" | wc -l) -gt 1 ]]
```suggestion
    if (( $(printf "%s\n" "${udc_function_list[@]}" | grep -o "radxa-adbd@" | wc -l) > 1 ))
```

2024-01-25 08:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
>          return 1
这里返回错误会导致程序结束吧？

2024-01-25 08:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
>          msgbox "Only enable ADB on one OTG port at the same time"
```suggestion
        msgbox "radxa-adbd can be enabled at most on one given port. Please reduce your selection and try again."
```

2024-01-25 08:23 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
>          return 1
```suggestion
        return
```

2024-01-25 08:26 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        checklist_add "$service" "OFF"
```suggestion
      enabled)
          checklist_add "$service" "ON"
          ;;
      disabled)
          checklist_add "$service" "OFF"
```

2024-01-25 08:32 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        udc_function_list+=("$(checklist_getitem "$i")")
这个你测试过么？

2024-01-25 08:36 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
> +        udc_function_list+=("$(checklist_getitem "$i")")
测试过了，同时开启adb功能，会报错，然后回退到Hardware菜单

2024-01-25 08:50 UTC, RadxaYuntian approved these changes

2024-01-25 08:50 UTC, merged