Modify parse_dtbo to use multithreaded concurrency
radxa-pkg/rsetup pull request #33
Opened 2024-01-26 09:42 UTC by CodeChenL

2024-01-29 08:31 UTC, RadxaYuntian requested changes
两个都要修改数据访问模型。python里面对list读写没有保证线程安全

2024-01-29 08:31 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +results = []
多线程访问共享资源，要上锁

2024-01-29 08:31 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    results = [""] * (len(files) + 1)
```suggestion
```
上锁，然后用append函数来添加新元素，而不是直接访问元素内容

2024-01-29 08:31 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +        futures = [executor.submit(process_file, file, compatible, i) for i, file in enumerate(files)]
append就不需要考虑i了

2024-01-29 08:31 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
看看我们最开始的bash实现，是不是并发查找后有排序

2024-01-29 09:27 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
https://github.com/radxa-pkg/rsetup/blob/f06452b775926fe72db932dab60525229538ba29/src/usr/lib/rsetup/tui/overlay/overlay.sh#L135最开始是解析完设备树后，加入checklist前再排序

2024-01-29 09:32 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
本来重构后我在 `parse_dtbo` 里进行排序，不然出去之后由于 `title` `status` `filename` 不是一行不好排序，后来被你否决了

2024-01-29 09:32 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
那我们也要在多线程处理结束后进行排序，否则由于是并行执行，无法保证结果顺序始终一致
这样需要在parse_dtbo里添加一个输出结果的类，已便于进行比较和排序

2024-01-29 09:36 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
> 后来被你否决了

是 #28 里面的么？好像没看到排序？

2024-01-29 09:37 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
> > 后来被你否决了
> 
> 是 #28 里面的么？好像没看到排序？

在这 https://github.com/radxa-pkg/rsetup/pull/28#discussion_r1442452451

2024-01-29 09:45 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
不过我也没进一步解释

2024-01-29 09:49 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
我现在这种方法也能保持输入输出一致，我觉得可以在此基础上加锁。还是乱序输入再排序？

2024-01-29 10:21 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
那也行吧，改用insert函数

2024-01-29 10:53 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
使用insert是不能保证顺序的，因为如果插入后list实际长度没有那么大，并不会在前面创建空值，然后插入到对应index,而是插到末尾

2024-01-29 10:54 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
那可以使用其他的数据结构，比如dictionary

2024-01-29 10:58 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
使用其他数据结构那和现在使用的list的赋值方式一样呀，results[index] = "***"

2024-01-29 10:59 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
为什么不能使用results[index] = "***"这种方式赋值呢

2024-01-29 11:09 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    print("".join(results), end="")
一般而言用method的话如果代码后续需要修改容易重构一些，operator reload比较容易导致一些意料之外的代码。不过就这个例子而言都可以

2024-01-29 11:46 UTC, RadxaYuntian requested changes

2024-01-29 11:46 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    results = [""] * len(files)
让你用别的数据结构就是不希望这样初始化啊。你现在这个初始化代码就是个O(n)的复杂度

2024-01-29 12:07 UTC, CodeChenL commented
用字典最后还是避免不了排序

2024-01-29 12:12 UTC, RadxaYuntian commented
目的不是避免排序，排序是多线程运行不可避免的一部分。
用字典目的是保证顺序和输入顺序一致，同时避免初始化没有被使用到的值

2024-01-29 12:15 UTC, RadxaYuntian requested changes

2024-01-29 12:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +                    results[index] = file + "\n"
最好把print给overlaod了，这样在保证数据不变的情况下，可以方便更改输出格式

2024-01-29 12:25 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +                    results[index] = file + "\n"
你指的是把`src/usr/lib/rsetup/mod/parse_dtbo`的 Result 类的 print 给overlaod吗

2024-01-30 02:45 UTC, RadxaYuntian requested changes

2024-01-30 02:45 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
> +    global results
results应该本身就是个global variable，应该不需要用global关键字吧？

2024-01-30 02:45 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +        results[index] = result
status(file)和basename(file)可以放到Result类里面，然后这里的解析内容可以变成Result(file)的constructor

2024-01-30 03:46 UTC, CodeChenL commented
先别review吧，感觉没按你意思改

2024-01-30 04:01 UTC, CodeChenL commented
> 先别review吧，感觉没按你意思改

好了

2024-01-30 08:15 UTC, RadxaYuntian requested changes

2024-01-30 08:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/dtbo_is_compatible
```suggestion
```
额外空行

2024-01-30 08:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +    def __init__(self, file = ""):
```suggestion
    def __init__(self, file):
```
空文件名对于我们的程序不是一个合法的输入。如果没有好的fallback选项就不要设置

2024-01-30 08:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +        return self.basename
用property来替代显式getter/setter：https://realpython.com/python-getter-setter/#using-properties-instead-of-getters-and-setters-the-python-way

status和basename是两个只读property（也就是没有setter），然后在property里面直接从file里面来生成返回值。field也是一个只读property。类的constructor则接收file和field两个参数，这样整个类就是immutable，避免误操作导致数据损坏

2024-01-30 08:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +    except Exception as e:
补一下注释说明在没有检测到metadata的时候的行为

2024-01-30 08:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +    result = Result(file)
```suggestion
```
在后面调用setField时再创建对象

2024-01-30 08:15 UTC, RadxaYuntian commented
优先处理这个pr，今天合并后会发布到测试镜像里面

2024-01-30 08:42 UTC, CodeChenL commented on src/usr/lib/rsetup/mod/parse_dtbo
> +    except Exception as e:
```suggestion
        result.setField(field)
    # If parsing a field fails, the return value will be handled according to the --default-value option
    except Exception as e:
```

2024-01-30 09:15 UTC, RadxaYuntian requested changes

2024-01-30 09:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +    def __init__(self,field , file):
```suggestion
    def __init__(self, field, file):
```

2024-01-30 09:18 UTC, RadxaYuntian requested changes

2024-01-30 09:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/mod/parse_dtbo
> +            return self.field + "\n" + self.status + "\n" + self.basename
```suggestion
            return f'{self.field}\n{self.status}\n{self.basename}'
```
interpolation看上去更自然一点：https://www.programiz.com/python-programming/string-interpolation

2024-01-30 09:22 UTC, RadxaYuntian commented
最后测一下吧，看看现在修改前后速度差距，并且确认功能正常

2024-01-30 09:30 UTC, CodeChenL commented
[test.txt](https://github.com/radxa-pkg/rsetup/files/14095588/test.txt)
附件为解析速度测试结果
rsetup可正常开启 overlay 与查看信息

2024-01-30 09:32 UTC, RadxaYuntian approved these changes

2024-01-30 09:32 UTC, CodeChenL commented
模拟checklist在overlays兼容性判断与解析上的耗时
从real    0m1.414s
缩短为real    0m1.414s

2024-01-30 09:33 UTC, merged