feat: add cli function enable_overlays
radxa-pkg/rsetup pull request #35
Opened 2024-02-18 07:59 UTC by CodeChenL

关联 https://github.com/radxa-pkg/rsetup/issues/34

2024-02-19 03:32 UTC, RadxaYuntian commented
要使用[GitHub支持的keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue)。如果可以的话最好写在commit消息里面

2024-02-19 03:47 UTC, RadxaYuntian requested changes

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +readonly ERROR_UPDATE_FAILED=-6
放到utils.sh那边

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    for i in "$@"
```suggestion

    for i in "$@"
```

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        if [[ $i == *.disabled ]]
```suggestion
        if [[ “$i” == *.disabled ]]
```
除非特殊情况，变量默认要用引号包括

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            if [ -e "$U_BOOT_FDT_OVERLAYS_DIR/$i" ]
```suggestion
            if [[ -e "$U_BOOT_FDT_OVERLAYS_DIR/$i" ]]
```
bash我们一律使用[[ ]]，这个更安全，也可以避免一些行为上的差异导致的问题

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +enable_overlays() {
声明你的local变量

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +                mv "$U_BOOT_FDT_OVERLAYS_DIR/$i" "$U_BOOT_FDT_OVERLAYS_DIR/$new_file_name"
你要两个循环，先在第一个循环判断输入是否合法并将合法输入解析后保存到一个数组里，如果有非法输入则报错并继续检查其余输入，然后终止执行
只有第一个循环通过了才执行第二个循环重命名，否则你的系统就可能既不是启动时的正确配置也不是用户想要更改成的新配置

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        msgbox "Selected overlays will be enabled at next boot."
cli方法一概不调用tui库
```suggestion
```

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    if u-boot-update >/dev/null
我们这里直接执行u-boot-update，让它把输出显示到终端即可，无需自定义额外的消息

2024-02-19 03:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    enable_overlays "${items[@]}"
在这里判断执行结果，解析返回值，然后msgbox回显给用户

2024-02-19 09:13 UTC, RadxaYuntian requested changes

2024-02-19 09:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +enable_overlays() {
按照其他语言的惯例变量声明是在代码前的，所以要放在`load_u-boot_setting`前面
另外`i`也是个变量

2024-02-19 09:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    local items
```suggestion
    local items ret
```

2024-02-19 09:13 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +    case $? in
```suggestion
    enable_overlays "${items[@]}"; ret="$?"
    case "$ret" in
```
我们有`set -e`，如果报错会直接终止执行

2024-02-21 02:08 UTC, CodeChenL commented
It's ready for review.

2024-02-21 06:26 UTC, RadxaYuntian reviewed
重新开一个pr

2024-02-21 07:03 UTC, RadxaYuntian requested changes

2024-02-21 07:03 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            echo "Overlay $i is already enabled" >&2
```suggestion
            echo "Overlay ‘$i’ is already enabled. Ignore." >&2
```

2024-02-21 07:03 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            echo "Overlay $i is not in $U_BOOT_FDT_OVERLAYS_DIR" >&2
```suggestion
            echo "Overlay ‘$i’ is not in ‘$U_BOOT_FDT_OVERLAYS_DIR’." >&2
```

2024-02-21 07:03 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            return "$ERROR_ILLEGAL_PARAMETERS"
看我们的需求定义啊，要返回所有的非法文件名，然后在循环结束后判断是否退出

2024-02-21 07:03 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
> +            msgbox "Have illegal parameters."
```suggestion
            msgbox "The selection contains non-existing overlays. Did you delete them?"
```
错误消息要能够让人理解，尤其是这种你知道为什么报错的情况下

2024-02-21 07:35 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        i="${i%.disabled}"
如果是相对路径呢，比如在/boot目录下输入dtbo/*

2024-02-21 07:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        i="${i%.disabled}"
相对路径realpath应该可以解析出来

2024-02-21 09:56 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        i="${i%.disabled}"
既然把目录填充成$U_BOOT_FDT_OVERLAYS_DIR
> 可以把目录填充成$U_BOOT_FDT_OVERLAYS_DIR

为什么要和$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")进行对比呢
> 并和$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")进行对比。这样后面的判断逻辑就可以简化

2024-02-21 09:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        i="${i%.disabled}"
可以把目录填充成$U_BOOT_FDT_OVERLAYS_DIR，**最后再给目录执行一遍realpath**来解析可能存在的符号链接，并和$(**realpath "$U_BOOT_FDT_OVERLAYS_DIR"**)进行对比。

2024-02-21 10:19 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        i="${i%.disabled}"
> 然后如果是不带全路径的话dirname会返回`.`，可以把目录填充成$U_BOOT_FDT_OVERLAYS_DIR

比如在/boot目录下输入dtbo/*,dirname不会返回`.`，或者说我们不接受相对路径，只接受绝对路径和文件名？

2024-02-21 11:39 UTC, RadxaYuntian requested changes

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        echo "$directory_name/$file_name"
```suggestion

```
调试输出

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            directory_name="$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")"
```suggestion
            directory_name="$U_BOOT_FDT_OVERLAYS_DIR"
```
后面会统一执行realpath

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        file_name="$(basename "$i")"
.disabled在这里去掉，整合后面的逻辑

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +    local enable_overlays_list i directory_name file_name have_illegal_parameters=false
```suggestion
    local enable_overlays_list i dir_name file_name input_check=true
```
名字可以稍微短一点
为了适应input_check的语义也把默认flag改成true

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +        if [[ "$(realpath "$directory_name")" == "$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")" ]]
```suggestion
        if [[ "$(realpath "$directory_name")" != "$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")" ]]
```
然后打印错误提示，设置input_flag为false，然后用continue关键字来跳过后面的判断，让循环继续检查下一个文件

2024-02-21 11:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +                [[ -e "$directory_name/$file_name" ]]
这种比较短的判断条件可以不用换行

2024-02-22 06:57 UTC, RadxaYuntian requested changes

2024-02-22 06:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            continue
```suggestion
```
你这里用if链后面的不会执行，不用continue

2024-02-22 06:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            echo "Overlay '$i' is not in '$U_BOOT_FDT_OVERLAYS_DIR'." >&2
```suggestion
            echo "$i: only overlays within '$U_BOOT_FDT_OVERLAYS_DIR' can be enabled." >&2
```

2024-02-22 06:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +           ! [[ -e "$dir_name/$file_name.disabled" ]] || ! [[ -e "$dir_name/$file_name.disabled" ]]
```suggestion
        if [[ "$(realpath "$dir_name")" != "$(realpath "$U_BOOT_FDT_OVERLAYS_DIR")" ]]
```
后面的判断和下面的有些重复，可以在这个if链的最后加一个else，然后提示`$file_name: cannot find such overlay in '$U_BOOT_FDT_OVERLAYS_DIR'.`并设置flag

2024-02-22 06:57 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/u-boot-menu.sh
> +            echo "Overlay '$i' is already enabled. Ignore." >&2
```suggestion
            echo "$file_name: already enabled." >&2
```

2024-02-22 07:14 UTC, RadxaYuntian approved these changes
squash一下

2024-02-22 07:26 UTC, merged