fix: fix rsetup.service running connect_wi-fi error on startup
radxa-pkg/rsetup pull request #39
Opened 2024-02-22 03:54 UTC by CodeChenL

* revised https://github.com/radxa-build/radxa-zero3/issues/7

2024-02-22 04:05 UTC, RadxaYuntian commented
要看看这个在首次启动没有网线连接时够不够快，以及在没有自带wifi的设备上测试看看网络会花多长时间online
如果首次启动不能尽快完成账户配置的话，用户无法登陆会很困扰的

2024-02-22 06:57 UTC, CodeChenL commented
首次启动没有网线连接的情况下，需要在第140秒左右才会创建rock用户

2024-02-22 07:01 UTC, RadxaYuntian commented
那要修改connect_wi-fi，在这里等待wifi就位
看看`nmcli radio wifi on`在wifi好和没好的时候错误输出以及返回值有什么区别

2024-02-22 09:10 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +connect_wi-fi_worker() {
那样这一大串代码就会重复两次？

2024-02-23 03:41 UTC, RadxaYuntian requested changes

2024-02-23 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                eval "$command"
```suggestion

            command=(nmcli dev wifi connect "$1")
            if (( $# == 2 ))
            then
                command+=(password "$2")
            fi

            for ((i = 0; i < 10; i++))
            do
                "${command[@]}"
```

2024-02-23 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                if ((result == 0))
直接if command不就好了

2024-02-23 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                    echo "WiFi connection successful"
```suggestion
                    echo "Wi-Fi successfully connected to '$1'."
```

2024-02-23 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                    echo "Failed, trying reconnection"
```suggestion
                    echo "Failed to connect to '$1'. Retry $((i + 1)) of $total_retry." >&2
```
加一个total_retry的定义，避免魔术数字

2024-02-23 03:41 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +            echo "Maximum number of tries reached, WiFi connection failed"
```suggestion
            echo "Wi-Fi failed to connect to '$1" after total of $total_retry retries. Quit." >&2
```
可以给$1也赋值给一个有意义的变量名。错误信息里引用了好几次

2024-02-26 03:43 UTC, RadxaYuntian requested changes

2024-02-26 03:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +    local i ssid="$1" password="$2" total_retry=10
我们有开启引用未定义变量报错的开关。如果你这里没有传入password会错误退出的，所以review说password的时候还是$2，没有像$1一样说要添加一个有意义的变量名
你有测试过你的代码么

2024-02-26 03:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +    local command=("nmcli device wifi connect $ssid")
你这样bash执行`"${command[@]}“`会找一个叫做`nmcli device wifi connect $ssid`的可执行文件，所以review里面只用引号包括了最后的变量字符串
用数组主要的目的就是为了`"${[@]}"`时会把每个数组元素都用引号包括，而不用操心可能存在的空格导致变量元素错位/拆分。否则就跟个字符串没有区别了

2024-02-26 03:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                if ${command[@]}
```suggestion
                if “${command[@]}”
```
凡是涉及到[@]引用数组的一概需要用引号

2024-02-26 03:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                # shellcheck disable=SC2068
```suggestion
```
shellcheck是对的

2024-02-26 03:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/wi-fi.sh
> +                    echo "Failed to connect to '$ssid'. Retry $((i + 1)) of '$total_retry'." >&2
```suggestion
                    echo "Failed to connect to '$ssid'. Retry $((i + 1)) of $total_retry." >&2
```
total_retry是我们自己定义的变量，并且知道是个数字，所以没必要用引号包括

2024-02-26 06:33 UTC, CodeChenL commented
> 现在这个版本可以在首次启动后正常连接么？行的话就重写一下历史

我测试一下，之前的测试是用终端和非首次启动测试的

2024-02-26 06:44 UTC, CodeChenL commented
> > 现在这个版本可以在首次启动后正常连接么？行的话就重写一下历史
> 
> 我测试一下，之前的测试是用终端和非首次启动测试的

已在首次启动测试通过

2024-02-26 07:00 UTC, RadxaYuntian approved these changes

2024-02-26 07:01 UTC, merged