refactor: replace tui dependency with librtui
radxa-pkg/rsetup pull request #43
Opened 2024-04-09 06:22 UTC by CodeChenL

2024-04-09 10:40 UTC, CodeChenL commented
> 同时debian/control要加上[类似这样](https://github.com/radxa-pkg/aic8800/blob/main/debian/control#L16)带版本的librtui依赖

librtui的下个版本是0.1.1吗

2024-04-09 11:13 UTC, RadxaYuntian requested changes
debian/control还要删掉whiptail的dependency，我会在librtui里面添加

2024-04-09 11:55 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/main.sh
> -source "/usr/lib/rsetup/mod/utils.sh"
对比了一下就多了这行https://github.com/radxa-pkg/rsetup/blob/4e475cc8a0aa6fcb37f30f074855e13cbbc9dfe3/src/usr/lib/rsetup/mod/utils.sh#L3

2024-04-09 12:12 UTC, RadxaYuntian requested changes

2024-04-09 12:12 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/main.sh
> +ALLOWED_RCONFIG_FUNC+=("log")
应该把log和这个定义放到https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/cli/rconfig.sh这里，然后把log从librtui中去掉

2024-04-10 02:23 UTC, RadxaYuntian requested changes

2024-04-10 02:23 UTC, RadxaYuntian commented on debian/control
> +         librtui (>= 0.1.1),
字母排序

2024-04-10 02:23 UTC, RadxaYuntian commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src $(OVERLAY_DIR)
应该可以多一个mount把librtui挂在到/usr/lib里面吧？这样后面的代码就不需要单独做判断

2024-04-10 06:28 UTC, RadxaYuntian requested changes
rebase

2024-04-10 06:28 UTC, RadxaYuntian commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src $(OVERLAY_DIR)
```suggestion
	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:./externals/librtui/src "$(OVERLAY_DIR)"
```

2024-04-10 06:28 UTC, RadxaYuntian commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=./externals/librtui/src:externals/librtui/examples "$(OVERLAY_DIR)/usr/lib/librtui"
```suggestion
	sudo mount -t overlay overlay -o lowerdir=./externals/librtui/src "$(OVERLAY_DIR)/usr/lib/librtui"
```
examples就不用挂载了，路径也不对

2024-04-10 06:45 UTC, CodeChenL commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src $(OVERLAY_DIR)
一开始我也是这么想的，但是在没有upperdir和workdir的情况下需要两个lowerdir

2024-04-10 06:46 UTC, CodeChenL commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src $(OVERLAY_DIR)
```shell
[chen@ChenArchLinux rsetup]$ make run
sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src /tmp/tmp.3s0Dcz5tKi
[sudo] password for chen: 
sudo mount -t overlay overlay -o lowerdir=./externals/librtui/src "/tmp/tmp.3s0Dcz5tKi/usr/lib/librtui"
mount: /tmp/tmp.3s0Dcz5tKi/usr/lib/librtui: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
make: *** [Makefile:17: overlay] Error 32
[chen@ChenArchLinux rsetup]$ sudo dmesg |grep overlayfs
[ 1877.546236] overlayfs: "xino" feature enabled using 3 upper inode bits.
[ 1877.558969] overlayfs: at least 2 lowerdir are needed while upperdir nonexistent
[chen@ChenArchLinux rsetup]$
```

2024-04-10 06:48 UTC, RadxaYuntian commented on Makefile
> +	sudo mount -t overlay overlay -o lowerdir=/:./src:./overlay:externals/librtui/src $(OVERLAY_DIR)
哦那其实可以用bind mount，别忘了设为只读

2024-04-10 07:08 UTC, RadxaYuntian approved these changes

2024-04-10 07:42 UTC, merged