feat: add the function to switch default target
radxa-pkg/rsetup pull request #49
Opened 2024-04-25 03:14 UTC by CodeChenL

* closed #47

2024-04-25 08:54 UTC, RadxaYuntian requested changes

2024-04-25 08:54 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    menu_add __system_target "System Default Target"
```suggestion
    menu_add __system_set_target "Change default boot target"
    menu_add __system_maintenance_menu "Maintenance"
```

2024-04-25 08:54 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    menu_add __system_maintenance_system_update "System Update"
这些函数名其实可以不去改变吧

2024-04-25 08:54 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    targets=(multi-user.target graphical.target)
```suggestion
    current_target="$(systemctl get-default)"
    available_targets=(multi-user.target graphical.target)
```
还要判断target是否存在吧。比如CLI系统应该就没有graphical

2024-04-25 08:54 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if ! radiolist_show "Please select the target to boot:" || (( ${#RTUI_RADIOLIST_STATE_NEW[@]} == 0 ))
```suggestion
    if ! radiolist_show "Please select the default boot target:

For CLI system, please choose 'multi-user.target'.
For desktop system, please choose 'graphical.target'." || (( ${#RTUI_RADIOLIST_STATE_NEW[@]} == 0 ))
```

2024-04-25 10:23 UTC, RadxaYuntian requested changes

2024-04-25 10:23 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    available_targets=("${available_targets[@]}")
直接在下面的for循环里面systemctl list-units判断不好么？如果不存在就continue跳过当前循环

2024-04-25 10:23 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if systemctl set-default "$(radiolist_getitem "${RTUI_RADIOLIST_STATE_NEW[0]}")"
```suggestion
    local new_target
    new_target="$(radiolist_getitem "${RTUI_RADIOLIST_STATE_NEW[0]}")"
    if systemctl set-default "$new_target"
```
相同代码重复三遍就可以考虑提取出来了

2024-04-25 11:34 UTC, RadxaYuntian requested changes

2024-04-25 11:34 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        if [[ "$(systemctl list-units -all --type=target)" != *"$i"* ]]
可以试着检查`systemctl list-units --legend=false "$i"`的输出

2024-04-25 11:34 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
>          if [[ "$i" == "$current_target" ]]
可以elif吧？

2024-04-25 11:34 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        msgbox "The default target has been set to ""$new_target"""
用单引号

2024-04-26 06:18 UTC, RadxaYuntian requested changes

2024-04-26 06:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        if [[ "$(systemctl list-units --legend=false "$i")" != "" ]]
```suggestion
        if [[ -z "$(systemctl list-units --legend=false "$i")" ]]
```
我们其他地方的空/非空判断应该都是用-z/-n来完成的

2024-04-26 06:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        msgbox "Failed to set the default target to '$new_target'"
```suggestion
        msgbox "Failed to set the default target to '$new_target'."
```

2024-04-26 06:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        msgbox "The default target has been set to '$new_target'"
```suggestion
        msgbox "The default target has been set to '$new_target'."
```

2024-04-26 06:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if systemctl set-default "$new_target"
看一看我们其他功能在成功/失败的提示是怎样的，现在感觉两个的提示很接近，没有区分度

2024-04-26 06:18 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +        return 1
用户选择cancel应该是返回0的吧，看看其他地方怎么操作的

2024-04-28 02:11 UTC, RadxaYuntian commented
放假结束了再来看这些

2024-05-11 02:36 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if systemctl set-default "$new_target"
我看了一下其他功能，也想不出怎么改

2024-05-11 02:45 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if systemctl set-default "$new_target"
好像是没有很好的办法。先在librtui里面添加一下配置和清除color scheme的函数，然后在错误消息这里临时把配色换成其他颜色。
color scheme可以参考https://stackoverflow.com/a/47179560

2024-05-11 02:46 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if systemctl set-default "$new_target"
我们用`NEWT_COLORS_FILE`来实现吧，就不要把配置直接写到脚本里面

2024-05-11 09:45 UTC, RadxaYuntian requested changes
另外整理一下提交

2024-05-11 09:45 UTC, RadxaYuntian commented on externals/librtui
也要更新`debian/control`里面对应的版本号

2024-05-11 10:07 UTC, RadxaYuntian requested changes

2024-05-11 10:07 UTC, RadxaYuntian commented on debian/control
> +         librtui (>> 0.1.1),
```suggestion
         librtui (>= 0.1.2),
```
`>> 0.1.1`可能会有一些带乱七八糟后缀的版本也能匹配上，还是就用下一个预计的版本0.1.2吧

2024-05-11 10:07 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
>      menu_add __system_system_update "System Update"
系统更新可以提到上面一级放到第一个，还是比较常用的

2024-05-11 10:07 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    menu_add __system_maintenance_menu "Maintenance"
```suggestion
    menu_add_separator
    menu_add __system_bootloader_menu "Bootloader Management"
```

2024-05-13 02:39 UTC, RadxaYuntian requested changes

2024-05-13 02:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
>  __system_maintenance_menu() {
函数名没改

2024-05-13 02:43 UTC, RadxaYuntian reviewed
rebase

2024-05-13 03:14 UTC, RadxaYuntian requested changes

2024-05-13 03:14 UTC, RadxaYuntian commented on debian/control
> +         librtui (>= 0.1.2),
这个改动应该在第一个提交里面

2024-05-13 06:48 UTC, RadxaYuntian approved these changes

2024-05-13 06:48 UTC, merged