Comm, hardware, system and user.
radxa-pkg/rsetup pull request #6
Opened 2022-08-15 09:17 UTC by cheanz

With those features completed, Chean modified hardware.sh after tests on board
Led list can function now.

Signed-off-by: cheanz<zhangchenge@radxa.com>

2022-08-15 09:53 UTC, RadxaYuntian requested changes
另外commit可以改动拆分成4个，不要提交一个很大的commit。

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/comm/comm.sh
>      msgbox "Configure Wi-Fi"
删掉占位用的UI

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/comm/comm.sh
> +    sudo nmtui
rsetup要求以root运行，不用sudo

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> -    msgbox "List LEDs"
List LED和Change LED Trigger是一个功能。先checklist列出LED以及当前的trigger，然后如果用户选中任何LED，继续进入到Change LED Trigger的界面。

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    msgbox "Update system"
删除占位指令

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    sudo apt update && sudo apt full-upgrade #| gauge “Please wait when updating system”
1.不要sudo
2.不要提交被注释掉的代码

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    local item item0
变量名要有意义，item我只是在test里面示例用的。
这里可以用new_password和new_password2

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    if [[ $? != 0 ]] ||[[ "$item" != "$item0" ]]
代码规范表达式之间要有空格

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    item=$(passwordbox "Please enter the new password:")
如果用户这里选择取消，则应该直接结束这个function。

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        msgbox "The passwards are not consistent."
The passwords you entered do not match.
然后代码可以改成一个循环，在这里判断不符后重新询问密码

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        if update_password "$(whoami)" "$item"
如果是sudo运行可能whoami返回的值不对

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            msgbox "Password has been changed to '$item'."
不要明文显示用户密码。直接提示The password has been changed.

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            update_password "$(whoami)" "$item"
这里不能这么操作。万一这次修改成功了呢？直接提示失败即可

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            msgbox "An error occured when trying to change password."
has occured

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    username=$(last | head -1 | cut -d ' ' -f1)
sudo后应该可以用$USER之类的获取当前用户

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    scanned_tty_services=$(ls /etc/systemd/system/getty.target.wants)
这个可能会有别的服务会希望在getty执行时被调用，要控制一下匹配的对象

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    msgbox "Here are available tty device services:${scanned_tty_services[@]}"
和下面的radiolist重复了

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    radiolist_init
可以用checklist，如果用户既希望串口登陆又希望hdmi登陆呢？

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        msgbox "User cancelled action."
不用提示用户取消操作，用户很清楚自己干了什么。直接return出去

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +#    device=$(inputbox "Enter your preferred tty device for auto login:tty1/ttyS0")
不要提交注释掉的代码

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    [Service]
cat << EOF会把下面的开头空格也写到文件中。都删掉

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    SYSTEMD_OVERRIDE=/etc/systemd/system/getty.target.wants/$selected_tty_device.d
字符串要用双引号包住

2022-08-15 09:53 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        AUTOLOGIN="ExecStart=-/sbin/agetty --autologin $username -o '-p -- \\\\u' --keep-baud 115200,57600,38400,9600 %I \$TERM"
最好是用grep去获取服务原本的参数，然后把修改后的参数写到override里面

2022-08-16 07:27 UTC, cheanz commented on root/lib/rsetup/tui/user/user.sh
> +    username=$(last | head -1 | cut -d ' ' -f1)
$USER，whoami 得到的是 root. 这个命令得到的是最后一个登录的用户的用户名。我测过了，应该没问题

2022-08-18 09:56 UTC, RadxaYuntian requested changes

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    menu_add __hardware_list_leds "List LEDs and change trigger"
直接把__hardware_list_leds的功能放到这里就可以了。只有一个选项的菜单没有必要

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    sudo apt update && sudo apt full-upgrade
1. &&应该是不需要的，我们有set -e，出错了会中断
2. 需要在full-upgrade之后加一个read -p “Press enter to continue..."给用户机会看最后的结果

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    "$ROOT_PATH/lib/rsetup/cli/system.sh" update_bootloader $mapped_board_name
判断命令是否执行成功，然后用msgbox显示结果

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    if [[ $? == 0 ]]
可以改写成
```
if (( $? != 0 ))
then
    return
fi
```
来减少代码缩进深度

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        while [[ $? == 0 ]]
应该是while循环在询问新密码的外面，然后密码匹配后退出循环，再修改密码

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +                msgbox "The passwards are not consistent."
https://www.google.com/search?q=the+password+does+not+match&newwindow=1&tbm=isch#imgrc=-BcIZqZJpIvzsM
参考一下常见的描述语言

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    scanned_tty_services=$(ls /etc/systemd/system/getty.target.wants | grep 'tty' |grep -v '.d')
|grep少了个空格

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    username="$(last | head -1 | cut -d ' ' -f1)"
声明成local

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    checklist_show "Choose the tty device/devices you prefer"
Please select the interface(s) you want to enable auto login:

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            selected_tty_real_index=$((3*${selected_tty_shrinked_index//\"}+1))
local

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            msgbox "Setting up auto login..."
这个堵塞了程序执行，不需要

2022-08-18 09:56 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    else
return提前，减少后面代码的缩进

2022-08-19 02:59 UTC, cheanz commented on root/lib/rsetup/tui/user/user.sh
> +        while [[ $? == 0 ]]
如果密码太短或者为空。passwd 命令实际上会无法更新密码。需要给一些提示信息吗？

2022-08-19 03:58 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        while [[ $? == 0 ]]
rsetup需要sudo运行，本身就不会被大部分密码强度策略限制。然后修改密码用的是chpasswd，测试用chpasswd修改密码为1可以成功

2022-08-19 04:01 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +                if update_password "$(last | head -1 | cut -d ' ' -f1)" "$new_passward"
用$(logname)，这个last判断不能保证是正确的（比如有用户ssh登陆）

2022-08-19 10:17 UTC, RadxaYuntian requested changes
另外在使用变量的时候尽量用双引号括起来

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +            saved_item+=(${itemselected})
可以和上一行合并

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    else
return提前，减少代码缩进

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +__hardware_change_led_trigger() {
可以并入__hardware_LED

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +        for trigger in $triggers
直接for `sed -E "s/\[(.*)\]/\1/" /sys/class/leds/input13\:\:capslock/trigger` 然后radiolist_add

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +            if [[ $trigger == *"["* ]]
没有意义，其他的LED可能目前不同的trigger，全部`radiolist_add "$trigger" "OFF"`

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    for selected_led in ${saved_item[@]} # scope??
不要这里循环，选择新trigger只执行一次，然后对所有上一步里选中的led通过循环应用新trigger

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    while [[ $? == 0 ]]
数值判断尽量用(( ))

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            msgbox "Passwords don't match. Try again"
循环要把第一次输入密码也包含进来，不然用户第一次输错第二次就永远也输不对了

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        return
函数结尾没有其他命令，这里不需要return

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        touch $SYSTEMD_OVERRIDE/override.conf
不需要touch，下面的tee会生成这个文件

2022-08-19 10:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +
删掉多余的空行

2022-08-23 09:01 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +        chosen_leds+=(${RSETUP_CHECKLIST[$index]})
这个chosen_leds可以访问LEDs_names吧？这样之后设置trigger时就不用正则去处理字符串了

2022-08-23 09:02 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +        echo $trigger_to_apply > $root_of_leds/$(echo $led | sed "s/\s*\[.*//g")/trigger
如果L27改一改这里可以不用sed

2022-08-23 09:03 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    if(( $? == 0 ))
应该可以直接`if ls /sys/class/leds/*/trigger &> /dev/null`

2022-08-23 09:03 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    if [[ $? != 0 ]]
用(( ))进行数值判断

2022-08-23 09:04 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    if [[ $? == 0 ]] && [[ ${#RSETUP_RADIOLIST_STATE_NEW[@]} -gt 0 ]]
用(( ${#RSETUP_RADIOLIST_STATE_NEW[@]} > 0 ))进行数值判断，提高可读性

2022-08-23 09:04 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    local root_dev="$(__get_root_dev)"
没用到的变量就删掉

2022-08-23 09:06 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    local mapped_board_name="$(echo "$cur_board_name" | tr , -)"
cur_board_name这个变量唯一的功能就是被echo，可以直接改成`$(dtname | tr , -)`

2022-08-23 09:07 UTC, RadxaYuntian commented on root/lib/rsetup/tui/system/system.sh
> +    if (( $? == 0 ))
可以和上面合并

2022-08-23 09:07 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    while (( 1 ))
一个优化技巧就是改用以下循环定义
```
local new_password=1
local new_password2
while [[ $new_password != $new_password2 ]]
```

2022-08-23 09:13 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            continue
然后这边的
```
    continue
else
    break
```
都可以删去。这样我们就能明确定义循环的退出条件，而不用在代码内寻找break

2022-08-23 09:13 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +            msgbox "Passwords don't match. Try again"
Passwords do not match. Please try again.
正式的书面语避免使用not缩写

2022-08-23 09:15 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        msgbox "Password has been changed."
The password

2022-08-23 09:15 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +        msgbox "An error has occured when trying to change password."
the password

2022-08-23 09:17 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    if (( $?!=0 )) || [[ ${#RSETUP_CHECKLIST_STATE_NEW[@]} -le 0 ]]
! checklist_show判断是否取消，然后用(( ))

2022-08-23 09:18 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    for selected_tty_shrinked_index in ${RSETUP_CHECKLIST_STATE_NEW[@]}
数组要用双引号括起来

2022-08-23 09:57 UTC, RadxaYuntian commented on root/lib/rsetup/tui/hardware/hardware.sh
> +    fi
看看issue里这个菜单有没有其他的功能，可能需要一个占位符确保菜单可以正确显示

2022-08-23 09:58 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +
添加一个yesno告知用户开启自动登录后当前用户的密码会被删除，将无法通过ssh登录，是否继续

2022-08-23 09:59 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
>  }
添加一个msgbox提升设置成功

2022-08-26 06:22 UTC, cheanz commented on root/lib/rsetup/tui/hardware/hardware.sh
> +        chosen_leds+=(${RSETUP_CHECKLIST[$index]})
这个chosen_leds获取的也是led[trigger]的形式而不是 led

2022-08-26 07:00 UTC, cheanz commented on root/lib/rsetup/tui/hardware/hardware.sh
> +        chosen_leds+=(${RSETUP_CHECKLIST[$index]})
没事了 用 ${RSETUP_CHECKLIST[$index]% *}处理

2022-09-06 03:54 UTC, RadxaYuntian requested changes
两个小问题，改好了就可以合并了

2022-09-06 03:54 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +
额外空行

2022-09-06 03:54 UTC, RadxaYuntian commented on root/lib/rsetup/tui/user/user.sh
> +    if ! yesno "After auto login is enabled, your current password will be deleted and login through SSH will be disabled.
your current password will be deleted, and you can only login SSH with public key.

2022-09-08 03:07 UTC, RadxaYuntian approved these changes

2022-09-08 03:08 UTC, merged