Add baota to rsetup
radxa-pkg/rsetup pull request #60
Opened 2024-06-14 08:51 UTC by RadxaPanda

This PR adds Baota panel to the common tasks section of rsetup

2024-06-14 11:11 UTC, RadxaYuntian requested changes
1. edit `src/usr/lib/rsetup/tui/main.sh` to show __task, probably need to change the title to "Applications"
2. Use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) in our code base. Commit title should be `feat: add support for Baota`

2024-06-14 11:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +            msgbox "Uninstall Baota success."
```suggestion
            msgbox "Baota is successfully uninstalled."
```

2024-06-14 11:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +            msgbox "Uninstall Baota failure."
```suggestion
            msgbox "An failure occurred when trying to uninstall Baota."  "$RTUI_PALETTE_ERROR"
```
$RTUI_PALETTE_ERROR can be used to display a red error message box.

2024-06-14 11:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +
```suggestion
```

2024-06-14 11:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +
```suggestion
```
Unnecessary new line

2024-06-14 11:11 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
>      menu_add __task_ssh             "SSH"
```suggestion
    if $DEBUG
    then
        menu_add __task_docker          "Docker"
        menu_add __task_ssh             "SSH"
    fi
```
Those 2 will need to be reworked. Hide them for now.

2024-06-14 11:17 UTC, RadxaYuntian commented
Your code also failed CI, so you probably did not install `pre-commit`.

2024-06-17 08:56 UTC, RadxaYuntian requested changes

2024-06-17 08:56 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/baota.sh
> +    curl -s https://download.bt.cn/install/install-ubuntu_6.0.sh | sudo bash /dev/stdin ed8484bec
```suggestion
    sudo bash < <(curl -s "https://download.bt.cn/install/install-ubuntu_6.0.sh")
```
Please don't pin this to a specific commit. You know we ain't gonna come back, update, and validate for new commits, so just install the latest version, and redirect user's problem to Baota itself.

2024-06-17 08:56 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/baota.sh
> +    curl -s https://download.bt.cn/install/bt-uninstall.sh | sudo bash /dev/stdin
```suggestion
    sudo bash < <(curl -s "https://download.bt.cn/install/bt-uninstall.sh")
```
Just to look a little bit nicer.

2024-06-17 08:56 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +    if [ -f /www/server/panel/BT-Panel ]
```suggestion
    if [[ -f /www/server/panel/BT-Panel ]]
```
`[ ]` should [generally be avoided](https://unix.stackexchange.com/questions/67172/vs-which-one-to-use-in-bash-scripts).

2024-06-19 02:27 UTC, RadxaYuntian requested changes
You can click `Re-request review` to notify me. Save a few types.
![image](https://github.com/radxa-pkg/rsetup/assets/95260730/8de4ff75-7b99-45dc-823a-0ac462c12dbe)
You can also squash your commits now.

2024-06-19 02:28 UTC, RadxaYuntian commented
Also conventional commit's tag(`chore`, `feat`, `fix`, etc) and the first world of the real commit title is starting in lower case.

2024-06-19 05:57 UTC, RadxaPanda commented
Squashed and pushed

2024-06-19 07:04 UTC, RadxaYuntian approved these changes
Lower case "A" next time.

2024-06-19 07:05 UTC, merged