feat: cli: add autologin function
radxa-pkg/rsetup pull request #62
Opened 2024-06-19 02:50 UTC by CodeChenL

2024-06-19 02:51 UTC, CodeChenL commented
@RadxaYuntian 先提交cli部分，接口稳定了再写tui

2024-06-19 03:10 UTC, RadxaYuntian reviewed
TUI的操作流程应该是这样：
1. 检测可以被配置的选项（查询enabled的getty服务，检查哪些窗口管理器被安装）
2. 一个checklist选择需要开启的选项，并标记哪些服务已经开启（简单grep一下对应关键词就好）
3. 一个inputbox选择对应的用户（默认填入当前用户名）

基于这个流程，CLI应该提供一个统一的入口`set_autologin_status`，需要接收需配置的服务、登陆用户、以及状态；以及一个`get_autologin_status`，来查询当前状态。

2024-06-19 03:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        xmllint --shell /usr/share/gdm/gdm.schemas << EOF
说过了用户的配置不能写这里，就算是使用rsetup也算是用户配置
下次我们更新radxa-system-config就会使自动登陆失效

2024-06-19 03:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +    echo "XSession=plasma" > /var/lib/AccountsService/users/radxa
这个应该不需要吧，应该可以自动识别到对应的session

2024-06-19 03:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +Session=plasma
session需要指定？

2024-06-19 03:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +autologin-session=plasma
session需要指定？

2024-06-19 03:29 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +Session=plasma
SDDM需要

2024-06-19 03:29 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +autologin-session=plasma
LightDM需要

2024-06-19 03:35 UTC, RadxaYuntian commented
另外cli应该能安全的反复执行，比如多次on或多次off。TUI这边应该是一个循环内按照是否选中来全部都重新设置一遍，而不会去单独检查服务此前的状态。

2024-06-20 07:20 UTC, RadxaYuntian requested changes

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +
```suggestion
```

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +    local systemd_override="/etc/systemd/system/$1.d" switch="$2" execstart user="${3:-$USER}"
USER这边要弄个helper,先检查SUDO_USER和PKEXEC_UID这两个变量（UID要转换回用户名），都没有才用USER，不然就都是默认root自动登陆了
功能函数这边不自己提供默认值

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +
```suggestion
```

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        rm -rf "$systemd_override/override.conf"
```suggestion
        rm -f "$systemd_override/override.conf"
```
不是目录不用递归

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        mkdir -p "$systemd_override"
先检查一下有没有这个服务吧

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        cat << EOF | tee "$systemd_override"/override.conf >/dev/null
```suggestion
        cat << EOF > "$systemd_override"/override.conf
```
你应该是root

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        mkdir -p $config_dir
这个目录应该安装了就有，检查是否存在，不要自己创建吧

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +[Service]
```suggestion
# Auto generated by rsetup
# DO NOT MODIFY!
[Service]
```

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        rm -rf "$config_dir/autologin.conf"
```suggestion
        rm -f "$config_dir/50-rsetup-autologin.conf"
```
名字用一个用户一般不会取的

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +    serial-getty@ttyAML0|serial-getty@ttyFIQ0|getty@tty1)
```suggestion
    serial-getty@*|getty@*)
```

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        ;;
```suggestion
    sddm|gdm|lightdm)
        "set_$item_autologin" "$switch" "$user"
        ;;
```

2024-06-20 07:20 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +get_autologin_status() {
这个函数应该还接收一个service的输入啊，你这个列表写死岂不是在TUI那边还要复制一份

2024-06-20 09:42 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +        mkdir -p $config_dir
这个目录，默认是没有的

2024-06-20 09:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +        mkdir -p $config_dir
我在zero上有，难道是启动后kde添加的？
![image](https://github.com/radxa-pkg/rsetup/assets/95260730/d13947e6-4b62-4c72-b78a-a8e0758f02b5)

2024-06-21 08:28 UTC, RadxaYuntian commented
#65 有一些获取当前用户的脚本，可以参考

2024-06-24 02:25 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +        mkdir -p $config_dir
我在rock5b上没有

2024-06-24 02:26 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +get_autologin_status() {
这里的接受参数需不需要改为单个服务，还是继续使用列表参数

2024-06-24 02:41 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/system.sh
> +    local systemd_override="/etc/systemd/system/$1.d" switch="$2" execstart user="${3:-$USER}"
这个helper感觉弄到librtui比较好？

2024-06-24 03:51 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +get_autologin_status() {
这里应该就是单个服务，循环之类在tui那边处理

2024-06-24 03:52 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/system.sh
> +    local systemd_override="/etc/systemd/system/$1.d" switch="$2" execstart user="${3:-$USER}"
先放rsetup吧，如果之后有别的代码需要再挪过去

2024-06-26 03:53 UTC, RadxaYuntian commented
librtui的更新先拆出去一个pr吧，这样panda那边也可以用上

2024-06-26 03:54 UTC, CodeChenL commented
> librtui的更新先拆出去一个pr吧，这样panda那边也可以用上

好的

2024-07-03 10:55 UTC, RadxaYuntian commented
刚刚注意到有一个__user_enable_auto_login

这是我目前用来在串口自动登陆的命令

```
mkdir -p /etc/systemd/system/serial-getty@.service.d/
cat << EOF > /etc/systemd/system/serial-getty\@.service.d/50-oem-autologin.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\\\u' --keep-baud --autologin oem --noclear 1500000,115200,57600,38400,9600 %I \$TERM
EOF
```

2024-07-03 10:55 UTC, RadxaYuntian commented
这个自动登陆的tui需要暴露出来供oem配置使用

2024-07-10 07:22 UTC, RadxaYuntian commented
修改了一些地方，麻烦测试一下

2024-07-10 07:22 UTC, RadxaYuntian commented
另外我们其实已有一个TUI了，也修改了一下来使用新的函数

2024-07-11 02:40 UTC, CodeChenL commented
> 修改了一些地方，麻烦测试一下

已测试，checklisth只有gdm, 可以正常开关autologin

2024-07-11 03:17 UTC, RadxaYuntian commented
这个是按照开启的服务来的，应该也有两个getty的才对

2024-07-17 03:38 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-07-17 04:00 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/user/user.sh
> +    done < <(systemctl list-units --state running --no-legend -- "*getty@*.service" sddm.service gdm.service lightdm.service)
现在修改后显示的服务发一下

2024-07-17 06:00 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/user/user.sh
> +    done < <(systemctl list-units --state running --no-legend -- "*getty@*.service" sddm.service gdm.service lightdm.service)
![image](https://github.com/user-attachments/assets/ef092fc4-68d5-4fba-bfb0-0b30075f890d)

2024-07-17 06:04 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/user/user.sh
> +    done < <(systemctl list-units --state running --no-legend -- "*getty@*.service" sddm.service gdm.service lightdm.service)
rsetup里面配置default target成multi-user看看

2024-07-17 09:43 UTC, RadxaYuntian requested changes
rebase 一下吧

2024-07-17 10:31 UTC, RadxaYuntian reviewed
本地的librtui不需要更新？https://github.com/radxa-pkg/rsetup/compare/d14a0180cceca3982f92af30193fa8dc07a72297..9e66f320f67a60744ca979af468d4c4844d3b260

2024-07-17 10:36 UTC, CodeChenL commented
> 本地的librtui不需要更新？https://github.com/radxa-pkg/rsetup/compare/d14a0180cceca3982f92af30193fa8dc07a72297..9e66f320f67a60744ca979af468d4c4844d3b260

一开始使用获取真实用户的utils需要更新，现在直接使用`logname`就不需要更新了

2024-07-17 10:40 UTC, RadxaYuntian approved these changes

2024-07-17 10:40 UTC, merged