fix: bootloader: add support judgment for operations
radxa-pkg/rsetup pull request #70
Opened 2024-07-18 10:30 UTC by CodeChenL

2024-07-18 10:47 UTC, RadxaYuntian requested changes

2024-07-18 10:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +            "$(( 256 + ERROR_ILLEGAL_PARAMETERS ))")
还要看看setup.sh里面的定义是不是一致的

2024-07-18 10:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    "$bootloader_method" "$bootloader"
```suggestion
        "$bootloader_method" "$bootloader"
```

2024-07-18 10:47 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if __assert_function "/usr/lib/u-boot/$bootloader/setup.sh" "$bootloader_method" && \
这个函数名字可能会变

2024-07-19 02:42 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/system/system.sh
> +            "$(( 256 + ERROR_ILLEGAL_PARAMETERS ))")
一致
```bash
rock@rock-5b:~$ cat /lib/librtui/utils/utils.sh | grep "ERROR" | grep -v -e "return" -e "if"        readonly ERROR_REQUIRE_PARAMETER=-1
        readonly ERROR_TOO_FEW_PARAMETERS=-2
        readonly ERROR_REQUIRE_FILE=-3
        readonly ERROR_ILLEGAL_PARAMETERS=-4
        readonly ERROR_REQUIRE_TARGET=-5
rock@rock-5b:~$ cat /lib/u-boot/rock-5b/setup.sh | grep "ERROR" | grep -v -e "return" -e "if"readonly ERROR_REQUIRE_FILE=-3
readonly ERROR_ILLEGAL_PARAMETERS=-4
readonly ERROR_REQUIRE_TARGET=-5
        exit "$ERROR_ILLEGAL_PARAMETERS"
rock@rock-5b:~$
```

2024-07-19 03:10 UTC, RadxaYuntian requested changes

2024-07-19 03:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
>          case "$ret" in
```suggestion
        case "$(( ret - 256 ))" in
```
这样后面的变量不用动

2024-07-19 06:15 UTC, RadxaYuntian requested changes

2024-07-19 06:15 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/system/system.sh
> +    if __external_script_type_check "/usr/lib/u-boot/$bootloader/setup.sh" "$bootloader_method" "function" 2>/dev/null && \
```suggestion
    if __external_script_type_check "/usr/lib/u-boot/$bootloader/setup.sh" "$bootloader_method" "function" && \
```
这个无所谓吧，就打印到stderr呗，反正一般也看不到

2024-07-19 06:34 UTC, RadxaYuntian requested changes
rebase，这应该算两个改动

2024-07-24 03:24 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/overlay/overlay.sh
>          0)
这个0明显跑不到了吧

2024-07-24 06:15 UTC, RadxaYuntian requested changes
rebase

2024-07-24 07:19 UTC, RadxaYuntian approved these changes

2024-07-24 07:19 UTC, merged