fix: task: change to use checklist
radxa-pkg/rsetup pull request #77
Opened 2024-08-06 08:20 UTC by CodeChenL

2024-08-06 08:30 UTC, RadxaYuntian requested changes

2024-08-06 08:30 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
这个checklist只是一个抽象的任务列表，选中的是会执行的任务
有的任务没有简单的on/off状态，所以不能用现在这个设置

2024-08-06 08:42 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/task/task.sh
如何控制卸载？下一层界面控制？

2024-08-06 08:43 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
现在的task_baota不是会根据是否安装提供不同的选项么？就把这个变成checklist里面的任务就好了啊

2024-08-06 09:21 UTC, RadxaYuntian requested changes

2024-08-06 09:27 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/baota.sh
> +    wget -O "$temp" "https://download.bt.cn/install/install_lts.sh"
我看的是比较新的官网`https://www.bt.cn/new/download.html`

2024-08-06 09:28 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/baota.sh
> +    rm -rf /www/server/panel
我参考的这里`https://www.bt.cn/new/btcode.html`

2024-08-06 09:30 UTC, CodeChenL commented on src/usr/lib/rsetup/tui/task/task.sh
> +
调用的函数有yesno

2024-08-07 02:08 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/baota.sh
> +    wget -O "$temp" "https://download.bt.cn/install/install_lts.sh"
看看是不是可以不带他的hash，不然他以后升级我们也不可能单独跟着升级rsetup

2024-08-07 02:10 UTC, RadxaYuntian commented on src/usr/lib/rsetup/cli/baota.sh
> +    rm -rf /www/server/panel
那可能是要用`/etc/init.d/bt`来判断是否安装了

2024-08-07 02:16 UTC, RadxaYuntian requested changes

2024-08-07 02:16 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/hardware/hardware.sh
这是怎么弄进来的

2024-08-07 02:16 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +    local length tasks selected
tasks用大写全局变量的命名形式，避免重复

2024-08-07 02:16 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +
那你这个循环就没有意义了啊，还是要用户守着你等一个执行完了再确认下一个。就应该在循环前有一个最终确认，之后执行任务就不会再次确认了

2024-08-07 02:21 UTC, CodeChenL commented on src/usr/lib/rsetup/cli/baota.sh
> +    wget -O "$temp" "https://download.bt.cn/install/install_lts.sh"
不可以，会和panda的给的脚本一样卡在开始

2024-08-07 03:04 UTC, RadxaYuntian requested changes

2024-08-07 03:04 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +
没修复

2024-08-07 03:04 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +        TASKS+=("__task_baota_uninstall")
__task_baota_uninstall之类应该删掉，直接用install_baota，然后在循环开始前确认

2024-08-07 03:04 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +    local length TASKS selected
```suggestion
    local length RSETUP_TASK_CALLBACKS selected
```

2024-08-07 03:04 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        __task_baota
改成在这里source对应的文件吧，source的时候执行__task_baota里面的内容，避免新功能需要修改两个地方才能将对应的功能打开

2024-08-07 03:51 UTC, RadxaYuntian requested changes

2024-08-07 03:51 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +if [[ -f /www/server/panel/BT-Panel ]]
```suggestion
if [[ -f /etc/init.d/bt ]]
```

2024-08-07 03:51 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/baota/baota.sh
> +    checklist_add "Uninstall Baota" "OFF"
```suggestion
    checklist_add "Uninstall Baota" "OFF" “uninstall_baota”
```
又看了下有专门做一个RTUI_CHECKLIST_VALUE数组来保存自定义数据，然后用checklist_getitem来获取数据，应该不需要RSETUP_TASK_CALLBACKS
需要弄一个API参考了

2024-08-07 03:51 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        if yesno "Execute the selected tasks: ""${tasks[*]}""?"
这里提示的应该是checklist里面的名字，不是函数名。

2024-08-07 03:52 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +            if [[ "$selected" == "ON" ]]
另外这里的应该是输入，不是输出，要用RTUI_CHECKLIST_STATE_NEW来判断吧

2024-08-07 07:44 UTC, RadxaYuntian requested changes

2024-08-07 07:44 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        task_titles=()
变量初始化放到checklist_show后面，中间有执行外部代码

2024-08-07 07:44 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +            tasks+=("$(checklist_getitem "$i")")
tasks没有必要单独在这里处理，直接在下面执行时再去提取就好

2024-08-07 07:44 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        if yesno "Execute the selected tasks: ""${task_titles[*]}""?"
```suggestion
        if yesno "The following tasks will be run:
$(for i in "${RTUI_CHECKLIST_STATE_NEW[@]}"
do
        checklist_gettitle "$i"
done)

Are you sure?"
```

2024-08-07 07:44 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        task_titles=()
其实没有必要分配这两个变量

2024-08-07 08:26 UTC, RadxaYuntian requested changes

2024-08-07 08:26 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +    read -n 1 -s -r -p "Press any key to continue."
```suggestion
    read -rp "Press enter to continue..."
```
还是不要那么容易返回吧

2024-08-07 08:27 UTC, RadxaYuntian commented
改好了squash一下，另外别忘了ci报错

2024-08-07 08:39 UTC, RadxaYuntian requested changes
把这几个提示更新后再squash一下吧

2024-08-07 08:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        checklist_emptymsg "No available tasks, Please try to update rsetup."
```suggestion
        checklist_emptymsg "Currently there is no compatible tasks available on this device."
```

2024-08-07 08:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +        if ! checklist_show "Please select an option below:" || checklist_is_selection_empty
```suggestion
        if ! checklist_show "Please select all tasks you want to perform:" || checklist_is_selection_empty
```

2024-08-07 08:39 UTC, RadxaYuntian commented on src/usr/lib/rsetup/tui/task/task.sh
> +$(for i in "${RTUI_CHECKLIST_STATE_NEW[@]}"
```suggestion

$(for i in "${RTUI_CHECKLIST_STATE_NEW[@]}"
```

2024-08-07 08:47 UTC, RadxaYuntian approved these changes

2024-08-07 08:47 UTC, merged